# Generated by Django 6.0.5 on 2026-06-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_projectlink_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='available_for_hire',
            field=models.BooleanField(default=False, verbose_name='open to work'),
        ),
    ]
