# Generated by Django 5.2.9 on 2025-12-09 07:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevresurgeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hiring', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilename', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_profilename', message='Profile name can only contain alphanumeric characters and underscores', regex='^[a-zA-Z0-9_]+$')], verbose_name='Profile handle')),
                ('display_name', models.CharField(default='', max_length=255)),
                ('bio', models.TextField(blank=True, default='', verbose_name='About')),
                ('location', models.CharField(blank=True, default='', max_length=255, verbose_name='Lives in')),
                ('tags', models.CharField(blank=True, default='', help_text='Enter skills as a comma-separated list (ex: linux, bash, kubernetes).', max_length=255, verbose_name='Skills')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='userprofile_pics/')),
                ('linkedin_url', models.URLField(blank=True, help_text='Link to your LinkedIn profile', max_length=255, null=True, verbose_name='LinkedIn')),
                ('job_titles', models.CharField(blank=True, default='', help_text='Enter job titles as a comma-separated list (ex: DevOps Engineer, Site Reliability Engineer, Cloud Engineer).', max_length=255, verbose_name='Seeking job titles')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('devresurge_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usercatalog.devresurgeuser')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=50)),
                ('profile_url', models.URLField()),
                ('link_index', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usercatalog.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='usercatalog.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLinkClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('social_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='usercatalog.sociallink')),
                ('userprofile_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_link_clicks', to='usercatalog.userprofileview')),
            ],
        ),
    ]
