# Generated by Django 5.2.8 on 2025-12-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercatalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='job_titles',
            field=models.CharField(blank=True, default='', help_text='Enter job titles as a comma-separated list (ex: DevOps Engineer, Site Reliability Engineer, Cloud Engineer).', max_length=255, verbose_name='Seeking job titles'),
        ),
    ]
