# Generated by Django 5.2.9 on 2025-12-10 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercatalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
    ]
