# Generated by Django 5.2.9 on 2025-12-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercatalog', '0002_remove_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='github_url',
            field=models.URLField(blank=True, help_text='Link to your GitHub profile', max_length=255, null=True, verbose_name='GitHub'),
        ),
    ]
