# Generated by Django 5.2.8 on 2025-11-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercatalog', '0002_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='Link to your LinkedIn profile', max_length=255, null=True),
        ),
    ]
