# Generated by Django 5.2.8 on 2025-11-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercatalog', '0003_userprofile_linkedin_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='Link to your LinkedIn profile', max_length=255, null=True, verbose_name='LinkedIn'),
        ),
    ]
