# Generated by Django 5.2.8 on 2025-11-21 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercatalog', '0004_alter_userprofile_linkedin_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='devresurge_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usercatalog.devresurgeuser'),
        ),
    ]
