# Generated by Django 5.2.9 on 2025-12-10 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercatalog', '0004_remove_userprofile_github_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
    ]
