# Generated by Django 6.0.5 on 2026-07-27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="connection",
            name="message",
            field=models.CharField(
                blank=True,
                help_text="Optional note sent with the request.",
                max_length=280,
                verbose_name="message",
            ),
        ),
        migrations.AddField(
            model_name="connection",
            name="relation",
            field=models.CharField(
                choices=[
                    ("peer", "Peer"),
                    ("collaborator", "Collaborator"),
                    ("mentor", "Mentor"),
                    ("mentee", "Mentee"),
                    ("recruiter", "Recruiter"),
                    ("hiring", "Hiring"),
                    ("friend", "Friend"),
                    ("other", "Other"),
                ],
                default="peer",
                help_text="How you know each other.",
                max_length=20,
                verbose_name="relation",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="payload",
            field=models.CharField(
                blank=True,
                max_length=120,
                verbose_name="payload",
            ),
        ),
        migrations.AlterField(
            model_name="connection",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                    ("blocked", "Blocked"),
                ],
                db_index=True,
                default="pending",
                max_length=12,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("connection_request", "Connection request"),
                    ("connection_accepted", "Connection accepted"),
                    ("badge_earned", "Badge earned"),
                    ("quiz_passed", "Quiz passed"),
                ],
                max_length=32,
                verbose_name="kind",
            ),
        ),
        migrations.AddIndex(
            model_name="connection",
            index=models.Index(
                fields=["status", "relation"],
                name="conn_status_relation_idx",
            ),
        ),
    ]
